name: Push to GCR/GHCR GitHub Action

on:
  push:
    tags:
      - '*'  # Trigger on any tag push
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build-and-push-to-gcr-service-account:
    name: Build & push to GCR/GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}" ]; then
            echo "Secret is NOT available!"
            exit 1
          else
            echo "Secret is available."
          fi

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}

      - name: Build and push Docker image
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
          yes | gcloud auth configure-docker gcr.io
          docker system prune --all --force
          ./docker/vm_boot_images/build.sh -P
          docker system prune --all --force
          ./docker/vm_boot_images/build.sh -c -P
